### ISSUE TITLE
model weights

### ISSUE THREAD

**Issue by xuecheng990531** [lxa9867/PaintSeg#6]
Dear author, 
when running the script/paintseg.py file, it suggests that the models `/ldm/inpainting_big/last.ckpt` file is missing, where can I download the weights for this model?

**Comment by xuecheng990531** [comment]
`Namespace(box_init=False, dataset='datasets', dino_v2=False, gt=False, indir=None, iters=5, outdir='result', point_num=0, scribble_init=False, split=1, steps=5, use_crf=True)
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 387.25 M params.
Keeping EMAs of 418.
making attention of type 'none' with 512 in_channels
Working with z of shape (1, 3, 64, 64) = 12288 dimensions.
making attention of type 'none' with 512 in_channels
Using first stage also as cond stage.
Traceback (most recent call last):
  File "scripts/PaintSeg.py", line 501, in <module>
    model.load_state_dict(torch.load("models/ldm/inpainting_big/last.ckpt")["state_dict"],
  File "/icislab/volume1/lixuecheng/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/icislab/volume1/lixuecheng/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/icislab/volume1/lixuecheng/miniconda/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/ldm/inpainting_big/last.ckpt'`
